[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_BASE_URL = "https://shamba-ai-wqui.onrender.com"
  VITE_API_KEY = "supersecretapexkey"
  VITE_DEV_MODE = "false"
  VITE_DEBUG_MODE = "false"
