services:
  - type: web
    runtime: python
    name: shambaai-ml-service
    region: frankfurt  # or nearest to your Oracle DB (eu-frankfurt-1)
    buildCommand: cd ml_service && ./build.sh
    startCommand: cd ml_service && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ML_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ORACLE_USER
        sync: false
      - key: ORACLE_PASSWORD
        sync: false
      - key: ORACLE_DSN
        sync: false
      - key: ORACLE_WALLET_LOCATION
        value: /opt/render/project/src/wallet
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRATION_HOURS
        value: 24
      - key: ML_PORT
        value: 8000
      - key: DATA_DIR
        value: ./data
      - key: LD_LIBRARY_PATH
        value: $HOME/oracle/instantclient_21_12:$LD_LIBRARY_PATH